### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by stramel** [zacharytamas/atom-jasmine#11]
Any thoughts about es6 support?

**Comment by zacharytamas** [comment]
Hmm. That could be tricky, especially for developers that work in multiple environments (i.e. ES6 and non-ES6). It looks like Atom doesn't differentiate between the grammars: it's always just `js`. [This popular es6 plugin](https://github.com/hharnisc/atom-es6-javascript), for example, just adds all its snippets to the normal `js` grammar.

I guess we could use a similar approach as you're working on for single/double quotes to make it configurable but something like this would probably be project-dependent, so constantly going in the settings to flip it back and forth would be annoying. It'd also be annoying if you're in an ES5 world and your snippets keep adding in ES6 things you have to rewrite immediately. You'd stop using it.

A low-fi fix for that would be to have the ES6 ones have different prefixes but then you end up with two sets to keep in your head and I for one would get really confused and probably stop using them altogether since there's a 50/50 chance it doesn't work like I wanted.

What do you think?

**Comment by stramel** [comment]
I agree with you, both approaches that you presented aren't ideal and it doesn't seem like there is an easy way to handle it.

The other approach that comes to mind that you did not list was shelling it out to a separate package. However, we would run into the issue of overlapping prefixes. To fix that would be the same as the low-fi fix you suggested above.

The configuration one sounds nice but is a pain when switching projects that differ ES5 to ES6. I was thinking maybe a hotkey to Toggle between ES5 and ES6 might be an idea or support a config file of some sorts that would automatically switch the settings. (A lot of work for a snippet package)

All in all, it may be good to hold off on a decision until someone else brings up the need for ES6 support. Hopefully by then there will be a better option or we can get more feedback for the direction we should take it.
